name: Radius
favicon: null
layout_spectrum: 0.25997
typography_spectrum: 0.7935785027220845
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ddc4ae'
    - '#fefefe'
    - '#050209'
    - '#763521'
    - '#af6f54'
  brandStrength: 0
  lightness: 0.5596328941173851
  saturation: 0.41659348108805716
  rhythmicContrast: 0.5
purpose: []
