typography_spectrum: 0.7935785027220845
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.5119474
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.75
  brandStrength: 0
  rhythmicContrast: 0.6839904
  brandColors:
    - '#ddc4ae'
    - '#fefefe'
    - '#050209'
    - '#763521'
    - '#af6f54'
  lightness: 0.2287933
purpose: []
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Radius
