name: Radius
favicon: null
layout_spectrum: 0.5119474
typography_spectrum: 0.7935785027220845
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Radius - The Ministry of Terri and Michael Sullivant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ddc4ae'
    - '#fefefe'
    - '#050209'
    - '#763521'
    - '#af6f54'
  brandStrength: 0
  lightness: 0.2287933
  saturation: 0.75
  rhythmicContrast: 0.6839904
purpose: []
